### ISSUE TITLE
Doesn't judge me

### ISSUE THREAD

**Issue by clearnote01** [paramsingh/poj#2]
Is it incomplete? POJ doesn't seem to judge me :/

**Comment by paramsingh** [comment]
It is indeed incomplete right now. A Pull Request would be most welcome! :P

**Comment by paramsingh** [comment]
@clearnote01 I have gotten judgement to work, I think. Check it out! Only works for C and C++ so far.

**Comment by clearnote01** [comment]
I was trying out python so that's why maybe... X)
Will see C/C++ later, congrats anyway!!
